INTERVAL_BACK: 2
INTERVAL_FIRST: 2
INTERVAL_NEXT: 1
LATEST_SOLUTION_DATE: '2025-08-10T16:45:05+00:00'
MESSAGES_FILE_PATH: data\discord_messages_names_pics.xlsx
NEXT_BATCH_FILE_PATH: data\discord_messages_names_pics.xlsx
SAVE_PATH: .\results
SOLUTIONS_DICT_FILENAME: solutions_dict.json
database:
  base_delay: 2.0
  connect_timeout: 60
  max_delay: 120.0
  max_overflow: 30
  max_retries: 5
  pool_pre_ping: true
  pool_recycle: 1800
  pool_size: 20
  pool_timeout: 120
  ssl_mode: prefer
  url: ${PEERA_DB_URL}
llm:
  batch_size: 10
  cache_ttl: 3600
  max_context_length: 8000
rag:
  embedding_dimension: 768
  embedding_model: text-embedding-004
  max_similar_results: 5
  similarity_threshold: 0.85
