INTERVAL_BACK: 2
INTERVAL_FIRST: 2
INTERVAL_NEXT: 1
LATEST_SOLUTION_DATE: '2025-08-19T15:08:35+00:00'
MESSAGES_FILE_PATH: data\discord_messages_correct.xlsx
NEXT_BATCH_FILE_PATH: data\discord_messages_correct.xlsx
SAVE_PATH: .\results
SOLUTIONS_DICT_FILENAME: solutions_dict.json
database:
  base_delay: 2.0
  connect_timeout: 60
  max_delay: 120.0
  max_overflow: 30
  max_retries: 5
  pool_pre_ping: true
  pool_recycle: 1800
  pool_size: 20
  pool_timeout: 120
  ssl_mode: prefer
  url: ${PEERA_DB_URL}
image_genai_cache: null
images:
  base_path: .\images
  cache_ttl: 86400
  gcs_bucket_name: discord_pics
  max_retries: 3
  timeout: 30
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/
llm:
  batch_size: 10
  cache_ttl: 3600
  max_context_length: 8000
  model_name: gemini-2.5-flash
rag:
  embedding_dimension: 768
  embedding_model: text-embedding-004
  max_similar_results: 5
  similarity_threshold: 0.85
